# Generated by Django 4.1.5 on 2023-02-04 10:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myadmin', '0002_brand_product_delete_otp'),
        ('customadmin', '0002_cart1_orders_delete_products_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart1',
            new_name='Cart',
        ),
    ]
