# Generated by Django 4.1.5 on 2023-02-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0003_rename_cart1_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Shipped', 'Shipped'), ('Cancelled by Customer', 'Cancelled by Customer'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Product Return', 'Product Return'), ('Product Return Approved', 'Product Return Approved')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('credit card', 'credit card'), ('Cash on Delivery', 'Cash On Delivery'), ('PayPal', 'PayPal')], default='Select', max_length=50),
        ),
    ]
