# Generated by Django 4.1.5 on 2023-02-04 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('offer_price', models.FloatField()),
                ('description', models.TextField()),
                ('stock', models.PositiveBigIntegerField(default=0)),
                ('category', models.CharField(choices=[('Watches for Men', 'Watches for Men'), ('Watches for Women', 'Watches for Women'), ('Watches for Unisex', 'Watches for Unisex')], max_length=50)),
                ('product_image', models.FileField(upload_to='productimg')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.brand')),
            ],
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
