# Generated by Django 4.1.5 on 2023-02-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_productmultipleimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('discount_price', models.IntegerField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
