# Generated by Django 4.1.5 on 2023-02-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='discount',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='offer_active',
            field=models.BooleanField(default=False),
        ),
    ]
