# Generated by Django 4.1.5 on 2023-02-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
